version: '3.8'

services:
  db:
    image: postgres:15
    container_name: genomic_data_db
    restart: always
    environment:
      POSTGRES_DB: genomic_data
      POSTGRES_USER: genomic_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-genomic_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U genomic_user -d genomic_data"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
